name: Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html pytest-playwright
          playwright install --with-deps  # Install Playwright browsers with dependencies

      - name: Verify Pytest & Playwright Installation
        run: |
          pytest --version
          python -c "from playwright.sync_api import sync_playwright; print('Playwright OK')"

      - name: Run Pytest (Headless Mode) & Generate Report
        run: |
          mkdir -p reports
          python -m pytest python/tests/t_soucedemo_login.py --headless --html=reports/report.html --self-contained-html

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html
          retention-days: 7  # Store the report for 7 days
