name: Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html pytest-playwright  # Install required plugins
          playwright install  # Ensure browsers are installed (if using Playwright)

      - name: Verify Pytest Installation
        run: pytest --version  # Debugging step to check pytest installation

      - name: Run Pytest (Headless)
        run: python -m pytest python/tests/t_soucedemo_login.py --html=report/report.html --self-contained-html

      # Optional: Run Playwright Tests with --headed
      - name: Run Playwright Tests (if needed)
        if: always()
        run: pytest python/tests/t_soucedemo_login.py --headed
